services:
  postgres :
    container_name: postgres-db
    image: postgres:17-alpine
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - private
    restart: unless-stopped
    # set shared memory limit when using docker compose
    shm_size: 128mb

  sonarqube:
    container_name: sonarqube
    image: sonarqube:lts-community
    depends_on:
      - sonarqube-db
    environment:
      - SONARQUBE_JDBC_USERNAME=sonarqube
      - SONARQUBE_JDBC_PASSWORD=sonarpass
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube-db:5342/sonarqube
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    ports:
      - 9001:9000

  sonarqube-db:
    container_name: sonarqube-db
    image: postgres:17-alpine
    environment:
      - POSTGRES_DB=sonarqube
      - POSTGRES_USER=sonarqube
      - POSTGRES_PASSWORD=sonarpass
    volumes:
      - sonarqube_database:/var/lib/postgresql
      - sonarqube_database_data:/var/lib/postgresql/data
    ports:
      - 5342:5432

networks:
  private:
    driver: bridge

volumes:
  pg-data:
  sonarqube_database_data:
  sonarqube_bundled-plugins:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_database:
  sonarqube_extensions: